# Generated by Django 3.2.3 on 2021-06-06 20:31

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('full_name', models.CharField(max_length=55)),
                ('lecture_price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('description', models.TextField(max_length=6000)),
                ('platform', models.CharField(choices=[('', ''), ('Google Meet', 'Google Meet'), ('Microsoft Teams', 'Microsoft Teams'), ('Zoom', 'Zoom'), ('Facebook Messenger', 'Facebook Messenger'), ('Other', 'Other')], max_length=55)),
                ('subject', models.CharField(choices=[('', ''), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('English', 'English'), ('Russian', 'Russian')], default='', max_length=55)),
                ('image', models.ImageField(default='default.jpg', upload_to='teacher_profile_image')),
                ('is_active', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_time', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=84), blank=True, null=True, size=None)),
                ('status', models.CharField(choices=[('send', 'send'), ('Approve', 'Approve')], max_length=8)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.teachersprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
